services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3002:3000"
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
  node_modules: